module.exports = {
  "name": "Windfinder",
  "spot": "Tarifa Centro",
  "days": [
      {
          "date": "Wednesday, Jul 22",
          "hours": [
              {
                  "hour": 0,
                  "windspeed": 8,
                  "windgust": 11,
                  "winddirectionDegrees": 76,
                  "winddirectionLetters": "ENE",
                  "temperature": 22,
                  "wavedirection": 86,
                  "waveheight": 0.9,
                  "waveinterval": 7
              },
              {
                  "hour": 1,
                  "windspeed": 9,
                  "windgust": 11,
                  "winddirectionDegrees": 91,
                  "winddirectionLetters": "E",
                  "temperature": 23,
                  "wavedirection": 85,
                  "waveheight": 1,
                  "waveinterval": 7
              },
              {
                  "hour": 2,
                  "windspeed": 5,
                  "windgust": 6,
                  "winddirectionDegrees": 84,
                  "winddirectionLetters": "E",
                  "temperature": 23,
                  "wavedirection": 85,
                  "waveheight": 1,
                  "waveinterval": 7
              },
              {
                  "hour": 3,
                  "windspeed": 5,
                  "windgust": 8,
                  "winddirectionDegrees": 62,
                  "winddirectionLetters": "ENE",
                  "temperature": 21,
                  "wavedirection": 84,
                  "waveheight": 1,
                  "waveinterval": 7
              },
              {
                  "hour": 4,
                  "windspeed": 5,
                  "windgust": 8,
                  "winddirectionDegrees": 57,
                  "winddirectionLetters": "ENE",
                  "temperature": 21,
                  "wavedirection": 83,
                  "waveheight": 1,
                  "waveinterval": 7
              },
              {
                  "hour": 5,
                  "windspeed": 6,
                  "windgust": 8,
                  "winddirectionDegrees": 41,
                  "winddirectionLetters": "NE",
                  "temperature": 21,
                  "wavedirection": 83,
                  "waveheight": 0.9,
                  "waveinterval": 7
              },
              {
                  "hour": 6,
                  "windspeed": 5,
                  "windgust": 6,
                  "winddirectionDegrees": 56,
                  "winddirectionLetters": "NE",
                  "temperature": 20,
                  "wavedirection": 82,
                  "waveheight": 0.9,
                  "waveinterval": 7
              },
              {
                  "hour": 7,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 51,
                  "winddirectionLetters": "NE",
                  "temperature": 20,
                  "wavedirection": 81,
                  "waveheight": 0.9,
                  "waveinterval": 7
              },
              {
                  "hour": 8,
                  "windspeed": 2,
                  "windgust": 2,
                  "winddirectionDegrees": 66,
                  "winddirectionLetters": "ENE",
                  "temperature": 21,
                  "wavedirection": 81,
                  "waveheight": 0.9,
                  "waveinterval": 7
              },
              {
                  "hour": 9,
                  "windspeed": 2,
                  "windgust": 3,
                  "winddirectionDegrees": 150,
                  "winddirectionLetters": "SSE",
                  "temperature": 23,
                  "wavedirection": 80,
                  "waveheight": 0.9,
                  "waveinterval": 7
              },
              {
                  "hour": 10,
                  "windspeed": 3,
                  "windgust": 3,
                  "winddirectionDegrees": 182,
                  "winddirectionLetters": "S",
                  "temperature": 23,
                  "wavedirection": 79,
                  "waveheight": 0.8,
                  "waveinterval": 7
              },
              {
                  "hour": 11,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 198,
                  "winddirectionLetters": "SSW",
                  "temperature": 24,
                  "wavedirection": 78,
                  "waveheight": 0.8,
                  "waveinterval": 7
              },
              {
                  "hour": 12,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 194,
                  "winddirectionLetters": "SSW",
                  "temperature": 24,
                  "wavedirection": 77,
                  "waveheight": 0.8,
                  "waveinterval": 7
              },
              {
                  "hour": 13,
                  "windspeed": 3,
                  "windgust": 4,
                  "winddirectionDegrees": 170,
                  "winddirectionLetters": "S",
                  "temperature": 25,
                  "wavedirection": 76,
                  "waveheight": 0.8,
                  "waveinterval": 6
              },
              {
                  "hour": 14,
                  "windspeed": 5,
                  "windgust": 7,
                  "winddirectionDegrees": 135,
                  "winddirectionLetters": "SE",
                  "temperature": 25,
                  "wavedirection": 76,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 15,
                  "windspeed": 8,
                  "windgust": 9,
                  "winddirectionDegrees": 115,
                  "winddirectionLetters": "ESE",
                  "temperature": 26,
                  "wavedirection": 75,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 16,
                  "windspeed": 9,
                  "windgust": 10,
                  "winddirectionDegrees": 107,
                  "winddirectionLetters": "ESE",
                  "temperature": 26,
                  "wavedirection": 74,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 17,
                  "windspeed": 9,
                  "windgust": 10,
                  "winddirectionDegrees": 105,
                  "winddirectionLetters": "ESE",
                  "temperature": 26,
                  "wavedirection": 74,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 18,
                  "windspeed": 7,
                  "windgust": 8,
                  "winddirectionDegrees": 103,
                  "winddirectionLetters": "ESE",
                  "temperature": 26,
                  "wavedirection": 73,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 19,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 101,
                  "winddirectionLetters": "E",
                  "temperature": 25,
                  "wavedirection": 72,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 20,
                  "windspeed": 4,
                  "windgust": 5,
                  "winddirectionDegrees": 97,
                  "winddirectionLetters": "E",
                  "temperature": 25,
                  "wavedirection": 72,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 21,
                  "windspeed": 3,
                  "windgust": 3,
                  "winddirectionDegrees": 80,
                  "winddirectionLetters": "E",
                  "temperature": 24,
                  "wavedirection": 71,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 22,
                  "windspeed": 3,
                  "windgust": 3,
                  "winddirectionDegrees": 5,
                  "winddirectionLetters": "N",
                  "temperature": 22,
                  "wavedirection": 70,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 23,
                  "windspeed": 3,
                  "windgust": 3,
                  "winddirectionDegrees": 353,
                  "winddirectionLetters": "N",
                  "temperature": 22,
                  "wavedirection": 69,
                  "waveheight": 0.7,
                  "waveinterval": 6
              }
          ]
      },
      {
          "date": "Thursday, Jul 23",
          "hours": [
              {
                  "hour": 0,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 332,
                  "winddirectionLetters": "NNW",
                  "temperature": 22,
                  "wavedirection": 68,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 1,
                  "windspeed": 6,
                  "windgust": 7,
                  "winddirectionDegrees": 328,
                  "winddirectionLetters": "NNW",
                  "temperature": 22,
                  "wavedirection": 67,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 2,
                  "windspeed": 8,
                  "windgust": 10,
                  "winddirectionDegrees": 335,
                  "winddirectionLetters": "NNW",
                  "temperature": 22,
                  "wavedirection": 67,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 3,
                  "windspeed": 7,
                  "windgust": 9,
                  "winddirectionDegrees": 343,
                  "winddirectionLetters": "NNW",
                  "temperature": 22,
                  "wavedirection": 66,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 4,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 350,
                  "winddirectionLetters": "N",
                  "temperature": 22,
                  "wavedirection": 65,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 5,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 19,
                  "winddirectionLetters": "NNE",
                  "temperature": 22,
                  "wavedirection": 64,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 6,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 39,
                  "winddirectionLetters": "NE",
                  "temperature": 22,
                  "wavedirection": 62,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 7,
                  "windspeed": 8,
                  "windgust": 9,
                  "winddirectionDegrees": 40,
                  "winddirectionLetters": "NE",
                  "temperature": 22,
                  "wavedirection": 61,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 8,
                  "windspeed": 10,
                  "windgust": 10,
                  "winddirectionDegrees": 45,
                  "winddirectionLetters": "NE",
                  "temperature": 22,
                  "wavedirection": 60,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 9,
                  "windspeed": 10,
                  "windgust": 11,
                  "winddirectionDegrees": 59,
                  "winddirectionLetters": "ENE",
                  "temperature": 23,
                  "wavedirection": 53,
                  "waveheight": 0.5,
                  "waveinterval": 6
              },
              {
                  "hour": 10,
                  "windspeed": 10,
                  "windgust": 10,
                  "winddirectionDegrees": 73,
                  "winddirectionLetters": "ENE",
                  "temperature": 24,
                  "wavedirection": 47,
                  "waveheight": 0.5,
                  "waveinterval": 6
              },
              {
                  "hour": 11,
                  "windspeed": 10,
                  "windgust": 10,
                  "winddirectionDegrees": 88,
                  "winddirectionLetters": "E",
                  "temperature": 25,
                  "wavedirection": 41,
                  "waveheight": 0.5,
                  "waveinterval": 6
              },
              {
                  "hour": 12,
                  "windspeed": 9,
                  "windgust": 9,
                  "winddirectionDegrees": 107,
                  "winddirectionLetters": "ESE",
                  "temperature": 26,
                  "wavedirection": 40,
                  "waveheight": 0.5,
                  "waveinterval": 6
              },
              {
                  "hour": 13,
                  "windspeed": 7,
                  "windgust": 8,
                  "winddirectionDegrees": 124,
                  "winddirectionLetters": "SE",
                  "temperature": 27,
                  "wavedirection": 39,
                  "waveheight": 0.5,
                  "waveinterval": 5
              },
              {
                  "hour": 14,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 150,
                  "winddirectionLetters": "SSE",
                  "temperature": 28,
                  "wavedirection": 39,
                  "waveheight": 0.5,
                  "waveinterval": 5
              },
              {
                  "hour": 15,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 185,
                  "winddirectionLetters": "S",
                  "temperature": 27,
                  "wavedirection": 63,
                  "waveheight": 0.5,
                  "waveinterval": 5
              },
              {
                  "hour": 16,
                  "windspeed": 5,
                  "windgust": 5,
                  "winddirectionDegrees": 218,
                  "winddirectionLetters": "SW",
                  "temperature": 27,
                  "wavedirection": 88,
                  "waveheight": 0.5,
                  "waveinterval": 5
              },
              {
                  "hour": 17,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 243,
                  "winddirectionLetters": "WSW",
                  "temperature": 28,
                  "wavedirection": 113,
                  "waveheight": 0.5,
                  "waveinterval": 5
              },
              {
                  "hour": 18,
                  "windspeed": 7,
                  "windgust": 7,
                  "winddirectionDegrees": 254,
                  "winddirectionLetters": "WSW",
                  "temperature": 28,
                  "wavedirection": 113,
                  "waveheight": 0.5,
                  "waveinterval": 5
              },
              {
                  "hour": 19,
                  "windspeed": 7,
                  "windgust": 7,
                  "winddirectionDegrees": 267,
                  "winddirectionLetters": "W",
                  "temperature": 28,
                  "wavedirection": 113,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 20,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 285,
                  "winddirectionLetters": "WNW",
                  "temperature": 28,
                  "wavedirection": 114,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 21,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 315,
                  "winddirectionLetters": "NW",
                  "temperature": 26,
                  "wavedirection": 151,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 22,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 8,
                  "winddirectionLetters": "N",
                  "temperature": 25,
                  "wavedirection": 189,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 23,
                  "windspeed": 5,
                  "windgust": 7,
                  "winddirectionDegrees": 12,
                  "winddirectionLetters": "NNE",
                  "temperature": 24,
                  "wavedirection": 227,
                  "waveheight": 0.6,
                  "waveinterval": 5
              }
          ]
      },
      {
          "date": "Friday, Jul 24",
          "hours": [
              {
                  "hour": 0,
                  "windspeed": 5,
                  "windgust": 7,
                  "winddirectionDegrees": 38,
                  "winddirectionLetters": "NE",
                  "temperature": 24,
                  "wavedirection": 247,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 1,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 61,
                  "winddirectionLetters": "ENE",
                  "temperature": 23,
                  "wavedirection": 267,
                  "waveheight": 0.6,
                  "waveinterval": 4
              },
              {
                  "hour": 2,
                  "windspeed": 6,
                  "windgust": 7,
                  "winddirectionDegrees": 72,
                  "winddirectionLetters": "ENE",
                  "temperature": 22,
                  "wavedirection": 287,
                  "waveheight": 0.6,
                  "waveinterval": 4
              },
              {
                  "hour": 3,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 61,
                  "winddirectionLetters": "ENE",
                  "temperature": 22,
                  "wavedirection": 288,
                  "waveheight": 0.6,
                  "waveinterval": 4
              },
              {
                  "hour": 4,
                  "windspeed": 8,
                  "windgust": 8,
                  "winddirectionDegrees": 54,
                  "winddirectionLetters": "NE",
                  "temperature": 22,
                  "wavedirection": 289,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 5,
                  "windspeed": 7,
                  "windgust": 7,
                  "winddirectionDegrees": 56,
                  "winddirectionLetters": "NE",
                  "temperature": 22,
                  "wavedirection": 290,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 6,
                  "windspeed": 7,
                  "windgust": 7,
                  "winddirectionDegrees": 64,
                  "winddirectionLetters": "ENE",
                  "temperature": 21,
                  "wavedirection": 290,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 7,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 68,
                  "winddirectionLetters": "ENE",
                  "temperature": 21,
                  "wavedirection": 290,
                  "waveheight": 0.7,
                  "waveinterval": 5
              },
              {
                  "hour": 8,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 71,
                  "winddirectionLetters": "ENE",
                  "temperature": 21,
                  "wavedirection": 291,
                  "waveheight": 0.7,
                  "waveinterval": 5
              },
              {
                  "hour": 9,
                  "windspeed": 5,
                  "windgust": 5,
                  "winddirectionDegrees": 99,
                  "winddirectionLetters": "E",
                  "temperature": 23,
                  "wavedirection": 291,
                  "waveheight": 0.7,
                  "waveinterval": 5
              },
              {
                  "hour": 10,
                  "windspeed": 4,
                  "windgust": 4,
                  "winddirectionDegrees": 150,
                  "winddirectionLetters": "SSE",
                  "temperature": 24,
                  "wavedirection": 291,
                  "waveheight": 0.7,
                  "waveinterval": 5
              },
              {
                  "hour": 11,
                  "windspeed": 6,
                  "windgust": 6,
                  "winddirectionDegrees": 230,
                  "winddirectionLetters": "SW",
                  "temperature": 24,
                  "wavedirection": 292,
                  "waveheight": 0.7,
                  "waveinterval": 5
              },
              {
                  "hour": 12,
                  "windspeed": 9,
                  "windgust": 10,
                  "winddirectionDegrees": 259,
                  "winddirectionLetters": "W",
                  "temperature": 25,
                  "wavedirection": 292,
                  "waveheight": 0.6,
                  "waveinterval": 5
              },
              {
                  "hour": 13,
                  "windspeed": 10,
                  "windgust": 11,
                  "winddirectionDegrees": 262,
                  "winddirectionLetters": "W",
                  "temperature": 25,
                  "wavedirection": 292,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 14,
                  "windspeed": 11,
                  "windgust": 11,
                  "winddirectionDegrees": 261,
                  "winddirectionLetters": "W",
                  "temperature": 26,
                  "wavedirection": 293,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 15,
                  "windspeed": 11,
                  "windgust": 11,
                  "winddirectionDegrees": 262,
                  "winddirectionLetters": "W",
                  "temperature": 26,
                  "wavedirection": 296,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 16,
                  "windspeed": 11,
                  "windgust": 12,
                  "winddirectionDegrees": 263,
                  "winddirectionLetters": "W",
                  "temperature": 26,
                  "wavedirection": 299,
                  "waveheight": 0.6,
                  "waveinterval": 6
              },
              {
                  "hour": 17,
                  "windspeed": 12,
                  "windgust": 13,
                  "winddirectionDegrees": 270,
                  "winddirectionLetters": "W",
                  "temperature": 27,
                  "wavedirection": 302,
                  "waveheight": 0.7,
                  "waveinterval": 6
              },
              {
                  "hour": 18,
                  "windspeed": 11,
                  "windgust": 12,
                  "winddirectionDegrees": 274,
                  "winddirectionLetters": "W",
                  "temperature": 27,
                  "wavedirection": 301,
                  "waveheight": 0.7,
                  "waveinterval": 7
              },
              {
                  "hour": 19,
                  "windspeed": 11,
                  "windgust": 13,
                  "winddirectionDegrees": 277,
                  "winddirectionLetters": "W",
                  "temperature": 27,
                  "wavedirection": 300,
                  "waveheight": 0.7,
                  "waveinterval": 7
              },
              {
                  "hour": 20,
                  "windspeed": 10,
                  "windgust": 13,
                  "winddirectionDegrees": 283,
                  "winddirectionLetters": "WNW",
                  "temperature": 26,
                  "wavedirection": 299,
                  "waveheight": 0.7,
                  "waveinterval": 8
              },
              {
                  "hour": 21,
                  "windspeed": 8,
                  "windgust": 13,
                  "winddirectionDegrees": 285,
                  "winddirectionLetters": "WNW",
                  "temperature": 25,
                  "wavedirection": 298,
                  "waveheight": 0.7,
                  "waveinterval": 8
              },
              {
                  "hour": 22,
                  "windspeed": 8,
                  "windgust": 13,
                  "winddirectionDegrees": 298,
                  "winddirectionLetters": "WNW",
                  "temperature": 23,
                  "wavedirection": 298,
                  "waveheight": 0.6,
                  "waveinterval": 8
              }
          ]
      }
  ]
}